//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputSystem/ChestOpening.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ChestOpening : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ChestOpening()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ChestOpening"",
    ""maps"": [
        {
            ""name"": ""Chest"",
            ""id"": ""39bc6a0a-b6b0-4b25-9470-ced70f6eabe6"",
            ""actions"": [
                {
                    ""name"": ""OpenChest"",
                    ""type"": ""Button"",
                    ""id"": ""6139bb7e-b453-47c0-8d66-9980988d0c6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c8362c9d-3568-4b4b-91d6-24e9b01f5ab6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Chest"",
                    ""action"": ""OpenChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e849fb66-4311-4708-829d-d4d400d9ecd2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Chest"",
                    ""action"": ""OpenChest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Chest"",
            ""bindingGroup"": ""Chest"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Chest
        m_Chest = asset.FindActionMap("Chest", throwIfNotFound: true);
        m_Chest_OpenChest = m_Chest.FindAction("OpenChest", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Chest
    private readonly InputActionMap m_Chest;
    private IChestActions m_ChestActionsCallbackInterface;
    private readonly InputAction m_Chest_OpenChest;
    public struct ChestActions
    {
        private @ChestOpening m_Wrapper;
        public ChestActions(@ChestOpening wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenChest => m_Wrapper.m_Chest_OpenChest;
        public InputActionMap Get() { return m_Wrapper.m_Chest; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ChestActions set) { return set.Get(); }
        public void SetCallbacks(IChestActions instance)
        {
            if (m_Wrapper.m_ChestActionsCallbackInterface != null)
            {
                @OpenChest.started -= m_Wrapper.m_ChestActionsCallbackInterface.OnOpenChest;
                @OpenChest.performed -= m_Wrapper.m_ChestActionsCallbackInterface.OnOpenChest;
                @OpenChest.canceled -= m_Wrapper.m_ChestActionsCallbackInterface.OnOpenChest;
            }
            m_Wrapper.m_ChestActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenChest.started += instance.OnOpenChest;
                @OpenChest.performed += instance.OnOpenChest;
                @OpenChest.canceled += instance.OnOpenChest;
            }
        }
    }
    public ChestActions @Chest => new ChestActions(this);
    private int m_ChestSchemeIndex = -1;
    public InputControlScheme ChestScheme
    {
        get
        {
            if (m_ChestSchemeIndex == -1) m_ChestSchemeIndex = asset.FindControlSchemeIndex("Chest");
            return asset.controlSchemes[m_ChestSchemeIndex];
        }
    }
    public interface IChestActions
    {
        void OnOpenChest(InputAction.CallbackContext context);
    }
}
